### Promise 原理

## 前置知识

  1）. 函数对象 与 实例对象

:::tip 实例对象 与 函数对象
  实例对象： new 操作符创建的对象，称为实例对象

  函数对象： 函数作为对象使用时，称为函数对象
:::

```js
    function Fn() {   // Fn函数
    }
    const fn = new Fn() // Fn是构造函数  fn是实例对象(简称为对象)
    console.log(Fn.prototype) // Fn是函数对象
    Fn.call({}) // Fn是函数对象
    $('#test') // jQuery函数
    $.get('/test') // jQuery函数对象

    function Person(params) {

    }
```

 2）. 同步回调 与 异步回调

::: tip sync callback and async callback

1）. 同步回调:

  理解: 立即执行, 完全执行完了才结束, 不会放入回调队列中

  例子: 数组遍历相关的回调函数 / Promise的excutor函数

2）. 异步回调:

  理解: 不会立即执行, 会放入回调队列中将来执行

  例子: 定时器回调 / ajax回调 / Promise的成功|失败的回调
:::

  ```js
  // 1. 同步回调函数
  // const arr = [1, 3, 5]
  arr.forEach(item => { // 遍历回调, 同步回调函数, 不会放入列队, 一上来就要执行完
    console.log(item)
  })
  console.log('forEach()之后')

  // 2. 异步回调函数
  setTimeout(() => { // 异步回调函数, 会放入队列中将来执行
    console.log('timout callback()')
  }, 0)
  console.log('setTimeout()之后')
  ```

  3）. JS常见异常处理

  ```js
目标: 进一步理解JS中的错误(Error)和错误处理
mdn文档: https: //developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Error
1. 错误的类型
    Error: 所有错误的父类型
    ReferenceError: 引用的变量不存在
    TypeError: 数据类型不正确的错误
    RangeError: 数据值不在其所允许的范围内
    SyntaxError: 语法错误
2. 错误处理
    捕获错误: try ... catch
    抛出错误: throw error
3. 错误对象
    message属性: 错误相关信息
    stack属性: 函数调用栈记录信息
  */

  // 1. 常见的内置错误
  // 1). ReferenceError: 引用的变量不存在
  // console.log(a) // ReferenceError: a is not defined
  // console.log('-----') // 没有捕获error, 下面的代码不会执行

  // TypeError: 数据类型不正确的错误
  // let b
  // // console.log(b.xxx) // TypeError: Cannot read property 'xxx' of undefined
  // b = {}
  // b.xxx() // TypeError: b.xxx is not a function


  // RangeError: 数据值不在其所允许的范围内
  // function fn() {
  //   fn()
  // }
  // fn() // RangeError: Maximum call stack size exceeded

  // SyntaxError: 语法错误
  // const c = """" // SyntaxError: Unexpected string


  // 2. 错误处理
  // 捕获错误: try ... catch
  // try {
  //   let d
  //   console.log(d.xxx)
  // } catch (error) {
  //   console.log(error.message)
  //   console.log(error.stack)
  // }
  // console.log('出错之后')

  // 抛出错误: throw error
function something() {
  if (Date.now()%2===1) {
    console.log('当前时间为奇数, 可以执行任务')
  } else { // 如果时间是偶数抛出异常, 由调用来处理
    throw new Error('当前时间为偶数无法执行任务')
  }
}

// 捕获处理异常
try {
  something()
} catch (error) {
  alert(error.message)
}

  ```
## Promise 理解 与 使用

### 2.1: 什么是Promise

:::tip 定义
1.抽象表达:
  Promise是JS中进行异步编程的新的解决方案(旧的是谁: callback hell, generator function)

2.具体表达:
  从语法上来说: Promise是一个构造函数
  从功能上来说: promise对象用来封装一个异步操作并可以获取其结果

3.promise的状态改变(只有2种, 只能改变一次)
  pending变为resolved

  pending变为rejected
:::

4.promise 基本流程
<img class='zoom-imgs' src='~@imgs/promise_flow.png' />

### 2.2: 为什么要用Promise

:::tip 优点
1. 指定回调函数的方式更加灵活: 可以在请求发出甚至结束后指定回调函数
2. 支持链式调用, 可以解决回调地狱问题
:::

### 2.3. 如何使用Promise

```js
// 1. 创建一个新的Promise对象
const p = new Promise((resolve, reject) => { // 执行器函数
    let time = Date.now()
// 2.执行异步操作
   setTimeout(() => {
        if(time % 2 === 1) { // 如果当前时间是偶数就代表成功， 否则代表失败
            resolve('成功的数据，time'  + time)
        } else {
            reject('失败的原因，time' + time)
        }
   }, 0)
})
p
.then(
    (val) => { // 接收成功的value数据 onResolved
         console.log(val)
        }, 
    (reason) => { // 接收失败的reason数据 onRejected
        console.log(reason)
    }
    )  // then 接受第二个回调(处理异常回调)， catch就无法捕获不到异常
.catch(reason => console.log(reason))
```
::: tip
1）. 主要API

Promise构造函数: Promise (excutor) {}

Promise.prototype.then方法: (onResolved, onRejected) => {}

Promise.prototype.catch方法: (onRejected) => {}

Promise.resolve方法: (value) => {}

Promise.reject方法: (reason) => {}

Promise.all方法: (promises) => {}

Promise.race方法: (promises) => {}

2）. 几个重要问题
如何改变promise的状态

一个promise指定多个成功/失败回调函数, 都会调用吗

promise.then()返回的新promise的结果状态由什么决定

改变promise状态和指定回调函数谁先谁后

promise如何串连多个操作任务

promise异常传(穿)透

中断promise链
:::
## 视频教程 以及文档

[Promise原理手写实现](https://www.bilibili.com/video/BV1MJ41197Eu?p=1)

[教程代码Code目录下](https://github.com/weolwo/promise-learn)

[WEB MDN Docs](https://developer.mozilla.org/zh-CN/)
